name: Tistory RSS to GitHub

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-blog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch Tistory RSS feed
      run: |
        if curl -s https://mw0606.tistory.com/rss -o tistory_feed.xml; then
          echo "RSS feed fetched successfully"
        else
          echo "Failed to fetch RSS feed" && exit 1
        fi

    - name: Commit RSS feed changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add tistory_feed.xml
        git diff --cached --quiet || git commit -m "Updated Tistory RSS feed at $(date +'%Y-%m-%d %H:%M:%S')"
        git push || echo "No changes to push"
